### Introduction to NumPy

#### Plan:
  - Create arrays
  - Multi-directional arrays
  - Randomly generated arrays
  - Element-wise operations
    - Comparison operations
    - Logical operations
  - Summarizing operations

In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/home/ray/miniconda3/envs/ml-zoomcamp/lib/python3.9/site-packages/numpy/__init__.py'>

#### Creating arrays

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
### instead of filling it with zeros, let's fill it with 1
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [6]:
# creating an array
a = np.array([1, 2, 3, 5, 7, 12])
a

array([ 1,  2,  3,  5,  7, 12])

In [7]:
a[2] = 10
a

array([ 1,  2, 10,  5,  7, 12])

In [8]:
# excluding the last element
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [9]:
np.linspace(3, 10, 5)

array([ 3.  ,  4.75,  6.5 ,  8.25, 10.  ])

#### Multi-dimensional arrays

In [10]:
# 5 rows and 2 columns
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
n = np.array([[1,2,3],[4,5,6], [7,8,9]])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
# accessing the multi dimensional array
n[1, 2] = 20
n

array([[ 1,  2,  3],
       [ 4,  5, 20],
       [ 7,  8,  9]])

In [13]:
# entire row in array
n[1] = [1, 1, 1]
n

array([[1, 2, 3],
       [1, 1, 1],
       [7, 8, 9]])

In [14]:
# entire column in array
n[:, 2] = [0, 1, 2]
n

array([[1, 2, 0],
       [1, 1, 1],
       [7, 8, 2]])

#### Randomly generated arrays

In [15]:
np.random.seed(2)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [16]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [17]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

#### Element-wise operations

In [18]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [19]:
# adding number to every element
a + 3

array([3, 4, 5, 6, 7])

In [20]:
# multiplying every element
a * 3

array([ 0,  3,  6,  9, 12])

In [21]:
# chain the operations
b = (10 + (a * 2)) ** 2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [22]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [23]:
a * b

array([ 0.  ,  1.44,  3.92,  7.68, 12.96])

In [24]:
a / b

array([0.        , 0.69444444, 1.02040816, 1.171875  , 1.2345679 ])

#### Comparison operations

In [25]:
a

array([0, 1, 2, 3, 4])

In [26]:
a >= 2

array([False, False,  True,  True,  True])

In [27]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [28]:
a > b

array([False, False,  True,  True,  True])

In [29]:
a[a > b]

array([2, 3, 4])

#### Summarizing operations

In [30]:
a

array([0, 1, 2, 3, 4])

In [31]:
a.min()

0

In [32]:
a.max()

4

In [33]:
a.mean()

2.0

In [34]:
a.sum()

10

In [35]:
a.std()

1.4142135623730951

In [36]:
# multi-dimensional array
n.sum()

23

In [37]:
n.min()

0